<?
$PERM["bitrix"]["*"]="D";
$PERM["lichnyy-kabinet-pokupatelya"]["6"]="W";
$PERM["lichnyy-kabinet-pokupatelya"]["*"]="D";
$PERM["lichnyy-kabinet-prodavtsa"]["7"]="W";
$PERM["lichnyy-kabinet-prodavtsa"]["*"]="D";
$PERM["/"]["*"]="R";
$PERM["search"]["5"]="W";
$PERM["company"]["5"]="W";
$PERM["index.php"]["5"]="W";
?>