<?
$PERM["lichnyy-kabinet-prodavtsa"]["8"]="W";
$PERM["lichnyy-kabinet-prodavtsa"]["7"]="R";
$PERM["lichnyy-kabinet-prodavtsa"]["*"]="D";
$PERM["lichnyy-kabinet-pokupatelya"]["8"]="W";
$PERM["lichnyy-kabinet-pokupatelya"]["6"]="R";
$PERM["lichnyy-kabinet-pokupatelya"]["*"]="D";
$PERM["upload"]["8"]="W";
$PERM["urlrewrite.php"]["8"]="W";
$PERM["index_inc.php"]["8"]="W";
$PERM["index.php"]["8"]="W";
$PERM["index.php"]["5"]="W";
$PERM[".top.menu.php"]["8"]="W";
$PERM[".left.menu.php"]["8"]="W";
$PERM[".bottom.menu.php"]["8"]="W";
$PERM["search"]["8"]="W";
$PERM["search"]["5"]="W";
$PERM["login"]["8"]="W";
$PERM["obyavleniya"]["8"]="W";
$PERM["o-servise"]["8"]="W";
$PERM["images"]["8"]="W";
$PERM["company"]["8"]="W";
$PERM["company"]["5"]="W";
$PERM["bitrix"]["*"]="D";
$PERM["/"]["*"]="R";
?>